language: python
python:
    - "3.6"
    - "3.8"
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
before_install:
  - pip install conllu
  - git clone -b master https://github.com/proycon/foliapy
  - cd foliapy
  - pip install .
  - cd ..
install:
  - pip install .
script:
  - cd test && bash test.sh
